[2022-06-23 18:43:14,239] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-21T00:00:00+00:00 [queued]>
[2022-06-23 18:43:14,249] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-21T00:00:00+00:00 [queued]>
[2022-06-23 18:43:14,249] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 18:43:14,249] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-06-23 18:43:14,249] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 18:43:14,259] {taskinstance.py:1264} INFO - Executing <Task(riot_matchDetailsToADLSOperator): staging_match_data> on 2022-06-21 00:00:00+00:00
[2022-06-23 18:43:14,264] {standard_task_runner.py:52} INFO - Started process 481 to run task
[2022-06-23 18:43:14,267] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'staging_match_data', 'scheduled__2022-06-21T00:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmpqitejlol', '--error-file', '/tmp/tmpeu3uh37r']
[2022-06-23 18:43:14,267] {standard_task_runner.py:77} INFO - Job 287: Subtask staging_match_data
[2022-06-23 18:43:14,309] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-21T00:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-23 18:43:14,353] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=staging_match_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-21T00:00:00+00:00
[2022-06-23 18:43:14,353] {riot_matchdetails_toADLS_Operator.py:63} INFO - StageToAzureLake not implemented yet
[2022-06-23 18:43:14,363] {riot_matchdetails_toADLS_Operator.py:72} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f9fd73c0880>>
[2022-06-23 18:43:14,364] {riot_matchdetails_toADLS_Operator.py:73} INFO - Created Azure Connection
[2022-06-23 18:43:14,372] {riot_matchdetails_toADLS_Operator.py:76} INFO - Created Riot Connection
[2022-06-23 18:43:15,337] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-23 18:43:15,338] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-23 18:43:15,338] {Limits.py:87} INFO - rate limit changed from 0/0s to 50/10s
[2022-06-23 18:43:15,339] {logging_mixin.py:109} INFO - [{'leagueId': '49ecb9ed-5b83-4b8f-9d0b-82c1a483ae0f', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'HdxS18ksOdstUGgfPIsfM4XNFuLAURXzpd91aMErixXM-E3J', 'summonerName': 'SmiteIsDeadGame', 'leaguePoints': 100, 'wins': 19, 'losses': 20, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '3077d668-5344-4f97-970b-4965e1d76f5a', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'etzoRcqNcxdfPl4zkLea-wPSMWpJBDkotzkQ8HQtsvBOuT2L', 'summonerName': 'tuotA', 'leaguePoints': 100, 'wins': 66, 'losses': 58, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': '8c0a55fe-faf9-4253-92ee-7c41d107892d', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'wARcLUntLspdDYkV4XpPw7h1rWbhqrEkHwi2O-qYXZH3jx47', 'summonerName': 'McR0an', 'leaguePoints': 100, 'wins': 38, 'losses': 29, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': '260b1565-e341-442b-baa2-f8d50b601f43', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'F-bB84IHd4qCn0HHu9ke6xK63_3-u-D1ATGBUvVexeew6kyo', 'summonerName': 'Nenya', 'leaguePoints': 100, 'wins': 68, 'losses': 78, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '241a8f12-26cd-4c5f-b002-ef7312c2d8bc', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'J5ft3DJjIbbyZq7MVZrcEh_xMKfBGElyzz-dc6Zueg6s4FdK', 'summonerName': 'topi conqueror', 'leaguePoints': 100, 'wins': 82, 'losses': 95, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '888bd458-9d5b-455b-a602-b0baa7c6a976', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'CUTAb4tcFsL1BmPDdYn_oi9VW3XBFX7bliK9cfz0zUCUUTha', 'summonerName': 'eeeeek', 'leaguePoints': 100, 'wins': 76, 'losses': 58, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': '57a24f47-03c4-4b53-b3dd-66da6b9bc902', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'cfiNlpD114V4KqBBcX1aAt7oAj8eMbjohupPGydEEoTLXFZn', 'summonerName': 'EnterRebirth', 'leaguePoints': 100, 'wins': 25, 'losses': 17, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '3311c1ba-3269-42ab-b059-be923729a75e', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'UbhzhrEbA8LuYZMhb0-iL88GriDSBXV_z-iq4u78PwILAt9R', 'summonerName': 'DlOR YOU', 'leaguePoints': 100, 'wins': 40, 'losses': 43, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 1, 'losses': 1, 'progress': 'LWNNN'}}, {'leagueId': 'b487adc5-8dae-41b8-9e14-39079d6fe783', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'auN_LuZip3rGOWBPfOwLo4M723GxmJgOZek-40RhgjGXk4H4', 'summonerName': 'NeekoNeekoN33', 'leaguePoints': 100, 'wins': 71, 'losses': 33, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 1, 'losses': 2, 'progress': 'WLLNN'}}, {'leagueId': '851c8032-0f57-4b3a-9f98-670180d61d2b', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'a9xKY_HTycsaAmfSp45dcVTPcB3J4jI64JlWsOOR-ty7FdTb', 'summonerName': 'COFFEE BEST DRUG', 'leaguePoints': 100, 'wins': 65, 'losses': 61, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}]
[2022-06-23 18:43:15,501] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2022-06-23 18:43:16,116] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-23 18:43:16,116] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-23 18:43:16,116] {Limits.py:87} INFO - rate limit changed from 0/0s to 500/10s
[2022-06-23 18:43:16,279] {Limits.py:87} INFO - rate limit changed from 0/0s to 250/10s
[2022-06-23 18:43:43,254] {RateLimiterAdapter.py:41} INFO - waiting for 92.861834 seconds...
[2022-06-23 18:45:19,164] {riot_matchdetails_toADLS_Operator.py:130} INFO - /tmp/tmpwkqd4jo7/match_details.csv
[2022-06-23 18:45:19,165] {_universal.py:472} INFO - Request URL: 'https://leagueoflegends.blob.core.windows.net/match-details/2022/6/23/18.csv?sv=REDACTED&ss=REDACTED&srt=REDACTED&sp=REDACTED&se=REDACTED&st=REDACTED&spr=REDACTED&sig=REDACTED'/nRequest method: 'PUT'/nRequest headers:/n    'x-ms-blob-type': 'REDACTED'/n    'Content-Length': '527808'/n    'If-None-Match': '*'/n    'x-ms-version': 'REDACTED'/n    'Content-Type': 'application/octet-stream'/n    'Accept': 'application/xml'/n    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.8.12 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'/n    'x-ms-date': 'REDACTED'/n    'x-ms-client-request-id': 'a144cd64-f324-11ec-b5a8-0242ac120006'/nA body is sent with the request
[2022-06-23 18:45:19,388] {_universal.py:503} INFO - Response status: 409/nResponse headers:/n    'Content-Length': '220'/n    'Content-Type': 'application/xml'/n    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'/n    'x-ms-request-id': '8ddc4d81-b01e-003a-2031-87a288000000'/n    'x-ms-client-request-id': 'a144cd64-f324-11ec-b5a8-0242ac120006'/n    'x-ms-version': 'REDACTED'/n    'x-ms-error-code': 'REDACTED'/n    'Date': 'Thu, 23 Jun 2022 18:45:21 GMT'
[2022-06-23 18:45:19,395] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8ddc4d81-b01e-003a-2031-87a288000000
Time:2022-06-23T18:45:21.8292016Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 64, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 131, in upload_to_azureLake
    wasb_hook.load_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 254, in load_file
    self.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 339, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:8ddc4d81-b01e-003a-2031-87a288000000
Time:2022-06-23T18:45:21.8292016Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8ddc4d81-b01e-003a-2031-87a288000000
Time:2022-06-23T18:45:21.8292016Z</Message></Error>
[2022-06-23 18:45:19,414] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=match_details_dag, task_id=staging_match_data, execution_date=20220621T000000, start_date=20220623T184314, end_date=20220623T184519
[2022-06-23 18:45:19,427] {standard_task_runner.py:89} ERROR - Failed to execute job 287 for task staging_match_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8ddc4d81-b01e-003a-2031-87a288000000
Time:2022-06-23T18:45:21.8292016Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 64, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 131, in upload_to_azureLake
    wasb_hook.load_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 254, in load_file
    self.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 339, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:8ddc4d81-b01e-003a-2031-87a288000000
Time:2022-06-23T18:45:21.8292016Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8ddc4d81-b01e-003a-2031-87a288000000
Time:2022-06-23T18:45:21.8292016Z</Message></Error>
[2022-06-23 18:45:19,442] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-23 18:45:19,476] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-24 00:25:20,421] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-21T00:00:00+00:00 [queued]>
[2022-06-24 00:25:20,431] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-21T00:00:00+00:00 [queued]>
[2022-06-24 00:25:20,432] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-24 00:25:20,432] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-06-24 00:25:20,432] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-24 00:25:20,442] {taskinstance.py:1264} INFO - Executing <Task(riot_matchDetailsToADLSOperator): staging_match_data> on 2022-06-21 00:00:00+00:00
[2022-06-24 00:25:20,447] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2022-06-24 00:25:20,451] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'staging_match_data', 'scheduled__2022-06-21T00:00:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmpnu9qcgix', '--error-file', '/tmp/tmpebvkkx9i']
[2022-06-24 00:25:20,452] {standard_task_runner.py:77} INFO - Job 342: Subtask staging_match_data
[2022-06-24 00:25:20,515] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-21T00:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-24 00:25:20,557] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=staging_match_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-21T00:00:00+00:00
[2022-06-24 00:25:20,557] {riot_matchdetails_toADLS_Operator.py:63} INFO - StageToAzureLake not implemented yet
[2022-06-24 00:25:20,567] {riot_matchdetails_toADLS_Operator.py:72} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f6f99a57fd0>>
[2022-06-24 00:25:20,568] {riot_matchdetails_toADLS_Operator.py:73} INFO - Created Azure Connection
[2022-06-24 00:25:20,577] {riot_matchdetails_toADLS_Operator.py:76} INFO - Created Riot Connection
[2022-06-24 00:25:20,903] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-24 00:25:20,903] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-24 00:25:20,903] {Limits.py:87} INFO - rate limit changed from 0/0s to 50/10s
[2022-06-24 00:25:20,904] {logging_mixin.py:109} INFO - [{'leagueId': 'c6dcc962-5d54-4bcf-9991-901dd6acda00', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'iMs6aSEysMHkgvAP6EYTPxJD-Sl78glMkmhNkL5teeVlhCGU', 'summonerName': 'Harukon', 'leaguePoints': 100, 'wins': 24, 'losses': 18, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '2f5e40b1-b909-41f0-9cbe-f281d6f40092', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'G1cpogdjZNzbBGChEgUOH9OQFqoV9NJGAgdsWtNq7jZTJUPy', 'summonerName': 'SirDur', 'leaguePoints': 100, 'wins': 60, 'losses': 32, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 2, 'losses': 1, 'progress': 'WWLNN'}}, {'leagueId': '574a3728-ceef-4f09-b163-e2e4aafed8f7', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'aF3YCmHsyYVDmlMx67rHoHYW01r4Ctx3Id2iZkJa61ewRHZ7', 'summonerName': 'Iron Four Life', 'leaguePoints': 100, 'wins': 25, 'losses': 23, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 1, 'losses': 0, 'progress': 'WNNNN'}}, {'leagueId': '3507019c-5cc7-44d9-8166-e68f9005c49a', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': '25_GY0jE0SxR8Mphq4WPXeWLCsITiMfZkFxX0PE5HI2uwfmt', 'summonerName': 'Matrix Divinity', 'leaguePoints': 100, 'wins': 44, 'losses': 21, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': 'ed607623-f7a5-44af-a642-3c0635b7dd0c', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'EjZhIVYtrVC4sUbA28970uwi9Fi-QNYCDeKwjBb8oIGCXnZm', 'summonerName': 'Mark Brnovich', 'leaguePoints': 100, 'wins': 20, 'losses': 25, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': '48dcac4a-66a6-4d86-b16b-ff35ae646524', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 't31xRPoLHcZqHt6bOXXLuH7ZAog4gdsVsRVWPrn471rAA83M', 'summonerName': 'Taquitoboi', 'leaguePoints': 100, 'wins': 24, 'losses': 33, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 1, 'losses': 1, 'progress': 'LWNNN'}}, {'leagueId': '54d9a544-5e7b-412d-a309-66815ad92913', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'a8ukyIW2Wawx8OFYh6kvU6XbMX-7l6I8FjKPdOiibfHDklBj', 'summonerName': 'Offensive Ward', 'leaguePoints': 100, 'wins': 17, 'losses': 12, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': 'bceb11be-188d-4f8c-8f9e-69597ebe92f0', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'imeCd9cTctBH1-_nbynvVW7uFyCmBC7Aby2tmM2KDvqvhsAN', 'summonerName': 'DenBlaze', 'leaguePoints': 100, 'wins': 38, 'losses': 40, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '9cc95895-54a8-496d-a4cd-ed25c42f9056', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': '3Si823od9hN3NUdmA2JLl8RRB-pcl-x8Zvb5hQiVTzs-s09G', 'summonerName': 'I just met you', 'leaguePoints': 100, 'wins': 131, 'losses': 89, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 2, 'losses': 2, 'progress': 'WLWLN'}}, {'leagueId': '3accc5cf-56d6-49df-b518-b38258d41010', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'fGXbh_w6vjIM6LrYiGWuLv7Scg9Nt0hPCIlp5Fk3xAAb567H', 'summonerName': 'Immora1', 'leaguePoints': 100, 'wins': 130, 'losses': 114, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 2, 'progress': 'LLNNN'}}]
[2022-06-24 00:25:20,985] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2022-06-24 00:25:21,257] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-24 00:25:21,257] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-24 00:25:21,257] {Limits.py:87} INFO - rate limit changed from 0/0s to 500/10s
[2022-06-24 00:25:21,489] {Limits.py:87} INFO - rate limit changed from 0/0s to 250/10s
[2022-06-24 00:25:47,575] {RateLimiterAdapter.py:41} INFO - waiting for 93.681592 seconds...
[2022-06-24 00:27:27,635] {riot_matchdetails_toADLS_Operator.py:130} INFO - /tmp/tmpmk6zt8sx/match_details.csv
[2022-06-24 00:27:27,636] {_universal.py:472} INFO - Request URL: 'https://leagueoflegends.blob.core.windows.net/match-details/GOLD/2022/6/24/0.csv?sv=REDACTED&ss=REDACTED&srt=REDACTED&sp=REDACTED&se=REDACTED&st=REDACTED&spr=REDACTED&sig=REDACTED'/nRequest method: 'PUT'/nRequest headers:/n    'x-ms-blob-type': 'REDACTED'/n    'Content-Length': '529274'/n    'If-None-Match': '*'/n    'x-ms-version': 'REDACTED'/n    'Content-Type': 'application/octet-stream'/n    'Accept': 'application/xml'/n    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.8.12 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'/n    'x-ms-date': 'REDACTED'/n    'x-ms-client-request-id': '6d30e578-f354-11ec-a14f-0242ac120005'/nA body is sent with the request
[2022-06-24 00:27:27,799] {_universal.py:503} INFO - Response status: 409/nResponse headers:/n    'Content-Length': '220'/n    'Content-Type': 'application/xml'/n    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'/n    'x-ms-request-id': '6b6eee0f-e01e-00cc-4461-87859e000000'/n    'x-ms-client-request-id': '6d30e578-f354-11ec-a14f-0242ac120005'/n    'x-ms-version': 'REDACTED'/n    'x-ms-error-code': 'REDACTED'/n    'Date': 'Fri, 24 Jun 2022 00:27:27 GMT'
[2022-06-24 00:27:27,801] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:6b6eee0f-e01e-00cc-4461-87859e000000
Time:2022-06-24T00:27:27.6866054Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 64, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 131, in upload_to_azureLake
    wasb_hook.load_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 254, in load_file
    self.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 339, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:6b6eee0f-e01e-00cc-4461-87859e000000
Time:2022-06-24T00:27:27.6866054Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:6b6eee0f-e01e-00cc-4461-87859e000000
Time:2022-06-24T00:27:27.6866054Z</Message></Error>
[2022-06-24 00:27:27,813] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=match_details_dag, task_id=staging_match_data, execution_date=20220621T000000, start_date=20220624T002520, end_date=20220624T002727
[2022-06-24 00:27:27,827] {standard_task_runner.py:89} ERROR - Failed to execute job 342 for task staging_match_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:6b6eee0f-e01e-00cc-4461-87859e000000
Time:2022-06-24T00:27:27.6866054Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 64, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 131, in upload_to_azureLake
    wasb_hook.load_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 254, in load_file
    self.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 339, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:6b6eee0f-e01e-00cc-4461-87859e000000
Time:2022-06-24T00:27:27.6866054Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:6b6eee0f-e01e-00cc-4461-87859e000000
Time:2022-06-24T00:27:27.6866054Z</Message></Error>
[2022-06-24 00:27:27,839] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-24 00:27:27,877] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
