[2022-06-21 03:43:00,086] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-20T07:00:00+00:00 [queued]>
[2022-06-21 03:43:00,096] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-20T07:00:00+00:00 [queued]>
[2022-06-21 03:43:00,096] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 03:43:00,096] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-06-21 03:43:00,097] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 03:43:00,107] {taskinstance.py:1264} INFO - Executing <Task(riot_matchDetailsToADLSOperator): staging_match_data> on 2022-06-20 07:00:00+00:00
[2022-06-21 03:43:00,111] {standard_task_runner.py:52} INFO - Started process 152 to run task
[2022-06-21 03:43:00,113] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'staging_match_data', 'scheduled__2022-06-20T07:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmprok04rjp', '--error-file', '/tmp/tmpzqxapmxu']
[2022-06-21 03:43:00,114] {standard_task_runner.py:77} INFO - Job 247: Subtask staging_match_data
[2022-06-21 03:43:00,160] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.staging_match_data scheduled__2022-06-20T07:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-21 03:43:00,208] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=staging_match_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-20T07:00:00+00:00
[2022-06-21 03:43:00,208] {riot_matchdetails_toADLS_Operator.py:61} INFO - StageToAzureLake not implemented yet
[2022-06-21 03:43:00,218] {riot_matchdetails_toADLS_Operator.py:70} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7fca29cc2940>>
[2022-06-21 03:43:00,218] {riot_matchdetails_toADLS_Operator.py:71} INFO - Created Azure Connection
[2022-06-21 03:43:00,226] {riot_matchdetails_toADLS_Operator.py:74} INFO - Created Riot Connection
[2022-06-21 03:43:00,556] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-21 03:43:00,556] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-21 03:43:00,556] {Limits.py:87} INFO - rate limit changed from 0/0s to 50/10s
[2022-06-21 03:43:00,557] {logging_mixin.py:109} INFO - [{'leagueId': '49ecb9ed-5b83-4b8f-9d0b-82c1a483ae0f', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'HdxS18ksOdstUGgfPIsfM4XNFuLAURXzpd91aMErixXM-E3J', 'summonerName': 'SmiteIsDeadGame', 'leaguePoints': 100, 'wins': 19, 'losses': 20, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '3077d668-5344-4f97-970b-4965e1d76f5a', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'etzoRcqNcxdfPl4zkLea-wPSMWpJBDkotzkQ8HQtsvBOuT2L', 'summonerName': 'tuotA', 'leaguePoints': 100, 'wins': 66, 'losses': 58, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': '8c0a55fe-faf9-4253-92ee-7c41d107892d', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'wARcLUntLspdDYkV4XpPw7h1rWbhqrEkHwi2O-qYXZH3jx47', 'summonerName': 'McR0an', 'leaguePoints': 100, 'wins': 38, 'losses': 29, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': 'e365fe8b-a022-4d34-b3ad-56a446fa2dc2', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'kOiM6a8VzO17NqXH_11qH4ECo0zUuGPJO3tMg8QK2PyHzIyd', 'summonerName': 'WzxBoyfriend', 'leaguePoints': 100, 'wins': 111, 'losses': 108, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '260b1565-e341-442b-baa2-f8d50b601f43', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'F-bB84IHd4qCn0HHu9ke6xK63_3-u-D1ATGBUvVexeew6kyo', 'summonerName': 'Nenya', 'leaguePoints': 100, 'wins': 68, 'losses': 78, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '241a8f12-26cd-4c5f-b002-ef7312c2d8bc', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'J5ft3DJjIbbyZq7MVZrcEh_xMKfBGElyzz-dc6Zueg6s4FdK', 'summonerName': 'topi conqueror', 'leaguePoints': 100, 'wins': 82, 'losses': 95, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '888bd458-9d5b-455b-a602-b0baa7c6a976', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'CUTAb4tcFsL1BmPDdYn_oi9VW3XBFX7bliK9cfz0zUCUUTha', 'summonerName': 'eeeeek', 'leaguePoints': 100, 'wins': 76, 'losses': 58, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': '57a24f47-03c4-4b53-b3dd-66da6b9bc902', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'cfiNlpD114V4KqBBcX1aAt7oAj8eMbjohupPGydEEoTLXFZn', 'summonerName': 'EnterRebirth', 'leaguePoints': 100, 'wins': 25, 'losses': 17, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '3311c1ba-3269-42ab-b059-be923729a75e', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'UbhzhrEbA8LuYZMhb0-iL88GriDSBXV_z-iq4u78PwILAt9R', 'summonerName': 'DlOR YOU', 'leaguePoints': 100, 'wins': 39, 'losses': 42, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': 'dd42a510-3686-40bb-b898-7be07caa8bd5', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'PLATINUM', 'rank': 'I', 'summonerId': 'xEVHiRr1cWeAheAXdH3uRrZhiYiRM8ZT8I1bhAAUxPssXOVM', 'summonerName': 'kkytj2', 'leaguePoints': 100, 'wins': 95, 'losses': 52, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}]
[2022-06-21 03:43:00,638] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2022-06-21 03:43:00,931] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-21 03:43:00,931] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-21 03:43:00,931] {Limits.py:87} INFO - rate limit changed from 0/0s to 500/10s
[2022-06-21 03:43:01,100] {Limits.py:87} INFO - rate limit changed from 0/0s to 250/10s
[2022-06-21 03:43:05,864] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/Handlers/ThrowOnErrorHandler.py", line 18, in after_request
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4286356015

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 62, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 90, in upload_to_azureLake
    match = riot_hook.get_match_byid(self.region, match)
  File "/opt/airflow/plugins/custom_hooks/riot_hook.py", line 30, in get_match_byid
    match_details = self.lol_watcher.match.by_id(my_region, match_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/helpers.py", line 32, in remapper
    return api_call(*nargs, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/league_of_legends/MatchApiV5.py", line 32, in by_id
    return self._request_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/NamedEndpoint.py", line 36, in _request_endpoint
    return self._base_api.raw_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/BaseApi.py", line 51, in raw_request
    mod = handler.after_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/Handlers/ThrowOnErrorHandler.py", line 20, in after_request
    raise ApiError(*err.args, request=err.request, response=err.response)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4286356015
[2022-06-21 03:43:05,881] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=match_details_dag, task_id=staging_match_data, execution_date=20220620T070000, start_date=20220621T034300, end_date=20220621T034305
[2022-06-21 03:43:05,899] {standard_task_runner.py:89} ERROR - Failed to execute job 247 for task staging_match_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/Handlers/ThrowOnErrorHandler.py", line 18, in after_request
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4286356015

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 62, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 90, in upload_to_azureLake
    match = riot_hook.get_match_byid(self.region, match)
  File "/opt/airflow/plugins/custom_hooks/riot_hook.py", line 30, in get_match_byid
    match_details = self.lol_watcher.match.by_id(my_region, match_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/helpers.py", line 32, in remapper
    return api_call(*nargs, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/league_of_legends/MatchApiV5.py", line 32, in by_id
    return self._request_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/NamedEndpoint.py", line 36, in _request_endpoint
    return self._base_api.raw_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/BaseApi.py", line 51, in raw_request
    mod = handler.after_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/Handlers/ThrowOnErrorHandler.py", line 20, in after_request
    raise ApiError(*err.args, request=err.request, response=err.response)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4286356015
[2022-06-21 03:43:05,919] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-21 03:43:05,963] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
