[2022-05-19 06:03:22,787] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:03:22,801] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:03:22,801] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:03:22,801] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 06:03:22,801] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:03:22,821] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_items.staging_items> on 2022-03-31 21:00:00+00:00
[2022-05-19 06:03:22,829] {standard_task_runner.py:52} INFO - Started process 334 to run task
[2022-05-19 06:03:22,834] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_items.staging_items', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmptsgisw5b', '--error-file', '/tmp/tmpe21zuktb']
[2022-05-19 06:03:22,835] {standard_task_runner.py:77} INFO - Job 152: Subtask paths.path_items.staging_items
[2022-05-19 06:03:22,913] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 06:03:22,980] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_items.staging_items
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 06:03:22,981] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 06:03:22,981] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3338ebb070>>
[2022-05-19 06:03:22,981] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 06:03:22,982] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = riot_hook.get_items(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:03:22,998] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_items.staging_items, execution_date=20220331T210000, start_date=20220519T060322, end_date=20220519T060322
[2022-05-19 06:03:23,013] {standard_task_runner.py:89} ERROR - Failed to execute job 152 for task paths.path_items.staging_items
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = riot_hook.get_items(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:03:23,047] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 06:12:36,739] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:12:36,759] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:12:36,759] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:12:36,759] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 06:12:36,759] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:12:36,779] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_items.staging_items> on 2022-03-31 21:00:00+00:00
[2022-05-19 06:12:36,786] {standard_task_runner.py:52} INFO - Started process 618 to run task
[2022-05-19 06:12:36,793] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_items.staging_items', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmp9t4l5v93', '--error-file', '/tmp/tmpwoj1ldx_']
[2022-05-19 06:12:36,794] {standard_task_runner.py:77} INFO - Job 157: Subtask paths.path_items.staging_items
[2022-05-19 06:12:36,892] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 06:12:36,985] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_items.staging_items
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 06:12:36,985] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 06:12:36,986] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f333146c2e0>>
[2022-05-19 06:12:36,986] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 06:12:36,986] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = riot_hook.get_items(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:12:37,010] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_items.staging_items, execution_date=20220331T210000, start_date=20220519T061236, end_date=20220519T061237
[2022-05-19 06:12:37,038] {standard_task_runner.py:89} ERROR - Failed to execute job 157 for task paths.path_items.staging_items
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = riot_hook.get_items(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:12:37,087] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 06:14:48,841] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:14:48,865] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:14:48,866] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:14:48,866] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 06:14:48,866] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:14:48,893] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_items.staging_items> on 2022-03-31 21:00:00+00:00
[2022-05-19 06:14:48,902] {standard_task_runner.py:52} INFO - Started process 698 to run task
[2022-05-19 06:14:48,908] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_items.staging_items', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpdigdul81', '--error-file', '/tmp/tmpl0r_ko1a']
[2022-05-19 06:14:48,909] {standard_task_runner.py:77} INFO - Job 160: Subtask paths.path_items.staging_items
[2022-05-19 06:14:49,015] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 06:14:49,125] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_items.staging_items
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 06:14:49,126] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 06:14:49,127] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3333ba4520>>
[2022-05-19 06:14:49,127] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 06:14:49,127] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = self.riot_hook.get_items(version=self.version)
TypeError: get_items() got multiple values for argument 'version'
[2022-05-19 06:14:49,154] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_items.staging_items, execution_date=20220331T210000, start_date=20220519T061448, end_date=20220519T061449
[2022-05-19 06:14:49,185] {standard_task_runner.py:89} ERROR - Failed to execute job 160 for task paths.path_items.staging_items
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = self.riot_hook.get_items(version=self.version)
TypeError: get_items() got multiple values for argument 'version'
[2022-05-19 06:14:49,202] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 07:31:38,685] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 07:31:38,699] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 07:31:38,699] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:31:38,699] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 07:31:38,699] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:31:38,713] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_items.staging_items> on 2022-03-31 21:00:00+00:00
[2022-05-19 07:31:38,719] {standard_task_runner.py:52} INFO - Started process 1416 to run task
[2022-05-19 07:31:38,724] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_items.staging_items', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpu__74vud', '--error-file', '/tmp/tmp90cfixy5']
[2022-05-19 07:31:38,725] {standard_task_runner.py:77} INFO - Job 192: Subtask paths.path_items.staging_items
[2022-05-19 07:31:38,793] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 07:31:38,937] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_items.staging_items
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 07:31:38,937] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 07:31:38,938] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f333146b2e0>>
[2022-05-19 07:31:38,938] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 07:31:38,939] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = self.riot_hook.get_items(version=self.version)
TypeError: get_items() got multiple values for argument 'version'
[2022-05-19 07:31:38,960] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_items.staging_items, execution_date=20220331T210000, start_date=20220519T073138, end_date=20220519T073138
[2022-05-19 07:31:38,983] {standard_task_runner.py:89} ERROR - Failed to execute job 192 for task paths.path_items.staging_items
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 67, in upload_to_azureLake
    response_data = self.riot_hook.get_items(version=self.version)
TypeError: get_items() got multiple values for argument 'version'
[2022-05-19 07:31:39,018] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-20 04:50:13,103] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-20 04:50:13,115] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-20 04:50:13,115] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 04:50:13,115] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-20 04:50:13,115] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 04:50:13,127] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_items.staging_items> on 2022-03-31 21:00:00+00:00
[2022-05-20 04:50:13,132] {standard_task_runner.py:52} INFO - Started process 5159 to run task
[2022-05-20 04:50:13,136] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_items.staging_items', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmplgwjwydf', '--error-file', '/tmp/tmp82hpkrn3']
[2022-05-20 04:50:13,136] {standard_task_runner.py:77} INFO - Job 668: Subtask paths.path_items.staging_items
[2022-05-20 04:50:13,192] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_items.staging_items scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-20 04:50:13,259] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_items.staging_items
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-20 04:50:13,259] {riot_datadragon_toADLS_Operator.py:55} INFO - StageToAzureLake not implemented yet
[2022-05-20 04:50:13,269] {riot_datadragon_toADLS_Operator.py:63} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f9ca8ceca30>>
[2022-05-20 04:50:13,269] {riot_datadragon_toADLS_Operator.py:64} INFO - Created Azure Connections
[2022-05-20 04:50:13,470] {riot_datadragon_toADLS_Operator.py:86} INFO - About to load to Azure!
[2022-05-20 04:50:13,470] {riot_datadragon_toADLS_Operator.py:87} INFO - items
[2022-05-20 04:50:13,472] {_universal.py:472} INFO - Request URL: 'https://leagueoflegends.blob.core.windows.net/datadragon-items/2022/5/20/4.json'/nRequest method: 'PUT'/nRequest headers:/n    'x-ms-blob-type': 'REDACTED'/n    'Content-Length': '259055'/n    'If-None-Match': '*'/n    'x-ms-version': 'REDACTED'/n    'Content-Type': 'application/octet-stream'/n    'Accept': 'application/xml'/n    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.8.12 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'/n    'x-ms-date': 'REDACTED'/n    'x-ms-client-request-id': '55e73a92-d7f8-11ec-afdd-0242ac140004'/n    'Authorization': 'REDACTED'/nA body is sent with the request
[2022-05-20 04:50:13,932] {_universal.py:503} INFO - Response status: 201/nResponse headers:/n    'Content-Length': '0'/n    'Content-MD5': 'REDACTED'/n    'Last-Modified': 'Fri, 20 May 2022 04:50:15 GMT'/n    'ETag': '"0x8DA3A1C3B4EC96E"'/n    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'/n    'x-ms-request-id': 'fc3f221e-c01e-0053-6d05-6cfd24000000'/n    'x-ms-client-request-id': '55e73a92-d7f8-11ec-afdd-0242ac140004'/n    'x-ms-version': 'REDACTED'/n    'x-ms-content-crc64': 'REDACTED'/n    'x-ms-request-server-encrypted': 'REDACTED'/n    'Date': 'Fri, 20 May 2022 04:50:15 GMT'
[2022-05-20 04:50:13,935] {riot_datadragon_toADLS_Operator.py:57} INFO - Upload league of legends data to Azure!
[2022-05-20 04:50:13,944] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=league_of_legends_dag, task_id=paths.path_items.staging_items, execution_date=20220331T210000, start_date=20220520T045013, end_date=20220520T045013
[2022-05-20 04:50:13,991] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-20 04:50:14,023] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
