[2022-05-19 08:13:46,736] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged manual__2022-05-19T08:13:44.090082+00:00 [queued]>
[2022-05-19 08:13:46,744] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged manual__2022-05-19T08:13:44.090082+00:00 [queued]>
[2022-05-19 08:13:46,744] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 08:13:46,745] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 08:13:46,745] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 08:13:46,755] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_runesreforged.staging_runesreforged> on 2022-05-19 08:13:44.090082+00:00
[2022-05-19 08:13:46,760] {standard_task_runner.py:52} INFO - Started process 1132 to run task
[2022-05-19 08:13:46,763] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_runesreforged.staging_runesreforged', 'manual__2022-05-19T08:13:44.090082+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpfx2vlet2', '--error-file', '/tmp/tmpts7mviyy']
[2022-05-19 08:13:46,763] {standard_task_runner.py:77} INFO - Job 248: Subtask paths.path_runesreforged.staging_runesreforged
[2022-05-19 08:13:46,806] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged manual__2022-05-19T08:13:44.090082+00:00 [running]> on host ca9a242fab95
[2022-05-19 08:13:46,850] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_runesreforged.staging_runesreforged
AIRFLOW_CTX_EXECUTION_DATE=2022-05-19T08:13:44.090082+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-19T08:13:44.090082+00:00
[2022-05-19 08:13:46,851] {riot_datadragon_toADLS_Operator.py:51} INFO - StageToAzureLake not implemented yet
[2022-05-19 08:13:46,860] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7fdd8516fe50>>
[2022-05-19 08:13:46,861] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 08:13:47,057] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 52, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 79, in upload_to_azureLake
    json.dump(response_data, fp)
NameError: name 'json' is not defined
[2022-05-19 08:13:47,066] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_runesreforged.staging_runesreforged, execution_date=20220519T081344, start_date=20220519T081346, end_date=20220519T081347
[2022-05-19 08:13:47,078] {standard_task_runner.py:89} ERROR - Failed to execute job 248 for task paths.path_runesreforged.staging_runesreforged
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 52, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 79, in upload_to_azureLake
    json.dump(response_data, fp)
NameError: name 'json' is not defined
[2022-05-19 08:13:47,097] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 08:13:47,125] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
