[2022-05-19 08:05:14,885] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_maps.staging_maps manual__2022-05-19T08:05:11.530364+00:00 [queued]>
[2022-05-19 08:05:14,899] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_maps.staging_maps manual__2022-05-19T08:05:11.530364+00:00 [queued]>
[2022-05-19 08:05:14,899] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 08:05:14,899] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 08:05:14,899] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 08:05:14,913] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_maps.staging_maps> on 2022-05-19 08:05:11.530364+00:00
[2022-05-19 08:05:14,920] {standard_task_runner.py:52} INFO - Started process 689 to run task
[2022-05-19 08:05:14,924] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_maps.staging_maps', 'manual__2022-05-19T08:05:11.530364+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpk326bzz2', '--error-file', '/tmp/tmpwc1mujc5']
[2022-05-19 08:05:14,925] {standard_task_runner.py:77} INFO - Job 223: Subtask paths.path_maps.staging_maps
[2022-05-19 08:05:14,984] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_maps.staging_maps manual__2022-05-19T08:05:11.530364+00:00 [running]> on host ca9a242fab95
[2022-05-19 08:05:15,042] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_maps.staging_maps
AIRFLOW_CTX_EXECUTION_DATE=2022-05-19T08:05:11.530364+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-19T08:05:11.530364+00:00
[2022-05-19 08:05:15,042] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 08:05:15,043] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7fdd72b52940>>
[2022-05-19 08:05:15,043] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 08:05:15,043] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 65, in upload_to_azureLake
    response_data = self.riot_hook.get_maps(self.version)
TypeError: get_maps() takes 1 positional argument but 2 were given
[2022-05-19 08:05:15,055] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_maps.staging_maps, execution_date=20220519T080511, start_date=20220519T080514, end_date=20220519T080515
[2022-05-19 08:05:15,072] {standard_task_runner.py:89} ERROR - Failed to execute job 223 for task paths.path_maps.staging_maps
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 65, in upload_to_azureLake
    response_data = self.riot_hook.get_maps(self.version)
TypeError: get_maps() takes 1 positional argument but 2 were given
[2022-05-19 08:05:15,096] {local_task_job.py:154} INFO - Task exited with return code 1
