[2022-06-20 23:11:05,791] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.dbt_run scheduled__2022-06-20T01:00:00+00:00 [queued]>
[2022-06-20 23:11:05,799] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.dbt_run scheduled__2022-06-20T01:00:00+00:00 [queued]>
[2022-06-20 23:11:05,799] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:11:05,799] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-06-20 23:11:05,799] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:11:05,808] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt_run> on 2022-06-20 01:00:00+00:00
[2022-06-20 23:11:05,812] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-06-20 23:11:05,814] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'dbt_run', 'scheduled__2022-06-20T01:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmp3w9kuil0', '--error-file', '/tmp/tmprrzn3vrz']
[2022-06-20 23:11:05,815] {standard_task_runner.py:77} INFO - Job 217: Subtask dbt_run
[2022-06-20 23:11:05,854] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.dbt_run scheduled__2022-06-20T01:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-20 23:11:05,892] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-20T01:00:00+00:00
[2022-06-20 23:11:05,892] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 23:11:05,893] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/dbt && dbt deps && dbt run']
[2022-06-20 23:11:05,901] {subprocess.py:85} INFO - Output:
[2022-06-20 23:11:08,439] {subprocess.py:89} INFO - 23:11:08  Running with dbt=1.1.0
[2022-06-20 23:11:09,222] {subprocess.py:89} INFO - 23:11:09  Installing dbt-labs/dbt_utils
[2022-06-20 23:11:09,768] {subprocess.py:89} INFO - 23:11:09    Installed from version 0.8.5
[2022-06-20 23:11:09,768] {subprocess.py:89} INFO - 23:11:09    Updated version available: 0.8.6
[2022-06-20 23:11:09,769] {subprocess.py:89} INFO - 23:11:09
[2022-06-20 23:11:09,769] {subprocess.py:89} INFO - 23:11:09  Updates available for packages: ['dbt-labs/dbt_utils']
[2022-06-20 23:11:09,769] {subprocess.py:89} INFO - Update your versions in packages.yml, then run dbt deps
[2022-06-20 23:11:13,614] {subprocess.py:89} INFO - 23:11:13  Running with dbt=1.1.0
[2022-06-20 23:11:13,700] {subprocess.py:89} INFO - 23:11:13  Found 17 models, 32 tests, 0 snapshots, 0 analyses, 400 macros, 0 operations, 0 seed files, 24 sources, 0 exposures, 0 metrics
[2022-06-20 23:11:13,704] {subprocess.py:89} INFO - 23:11:13
[2022-06-20 23:11:15,270] {subprocess.py:89} INFO - 23:11:15  Concurrency: 10 threads (target='dev')
[2022-06-20 23:11:15,270] {subprocess.py:89} INFO - 23:11:15
[2022-06-20 23:11:15,290] {subprocess.py:89} INFO - 23:11:15  1 of 16 START table model PUBLIC.final_champions ............................... [RUN]
[2022-06-20 23:11:15,294] {subprocess.py:89} INFO - 23:11:15  2 of 16 START table model PUBLIC.final_items ................................... [RUN]
[2022-06-20 23:11:15,296] {subprocess.py:89} INFO - 23:11:15  3 of 16 START table model PUBLIC.final_maps .................................... [RUN]
[2022-06-20 23:11:15,298] {subprocess.py:89} INFO - 23:11:15  4 of 16 START incremental model PUBLIC.final_match_details ..................... [RUN]
[2022-06-20 23:11:15,300] {subprocess.py:89} INFO - 23:11:15  5 of 16 START incremental model PUBLIC.final_match_info ........................ [RUN]
[2022-06-20 23:11:15,301] {subprocess.py:89} INFO - 23:11:15  6 of 16 START incremental model PUBLIC.final_players ........................... [RUN]
[2022-06-20 23:11:15,303] {subprocess.py:89} INFO - 23:11:15  7 of 16 START table model PUBLIC.final_runes_reforged .......................... [RUN]
[2022-06-20 23:11:15,305] {subprocess.py:89} INFO - 23:11:15  8 of 16 START table model PUBLIC.final_summonerspells .......................... [RUN]
[2022-06-20 23:11:15,306] {subprocess.py:89} INFO - 23:11:15  9 of 16 START view model PUBLIC.stg_champions .................................. [RUN]
[2022-06-20 23:11:15,308] {subprocess.py:89} INFO - 23:11:15  10 of 16 START view model PUBLIC.stg_items ..................................... [RUN]
[2022-06-20 23:11:17,823] {subprocess.py:89} INFO - 23:11:17  1 of 16 OK created table model PUBLIC.final_champions .......................... [[32mSUCCESS 1[0m in 2.53s]
[2022-06-20 23:11:17,830] {subprocess.py:89} INFO - 23:11:17  11 of 16 START view model PUBLIC.stg_maps ...................................... [RUN]
[2022-06-20 23:11:18,930] {subprocess.py:89} INFO - 23:11:18  9 of 16 OK created view model PUBLIC.stg_champions ............................. [[32mSUCCESS 1[0m in 3.62s]
[2022-06-20 23:11:18,933] {subprocess.py:89} INFO - 23:11:18  12 of 16 START view model PUBLIC.stg_match_details ............................. [RUN]
[2022-06-20 23:11:19,010] {subprocess.py:89} INFO - 23:11:19  6 of 16 OK created incremental model PUBLIC.final_players ...................... [[32mSUCCESS 1[0m in 3.71s]
[2022-06-20 23:11:19,014] {subprocess.py:89} INFO - 23:11:19  13 of 16 START view model PUBLIC.stg_match_info ................................ [RUN]
[2022-06-20 23:11:19,637] {subprocess.py:89} INFO - 23:11:19  10 of 16 OK created view model PUBLIC.stg_items ................................ [[32mSUCCESS 1[0m in 4.33s]
[2022-06-20 23:11:19,638] {subprocess.py:89} INFO - 23:11:19  14 of 16 START view model PUBLIC.stg_players ................................... [RUN]
[2022-06-20 23:11:19,697] {subprocess.py:89} INFO - 23:11:19  11 of 16 OK created view model PUBLIC.stg_maps ................................. [[32mSUCCESS 1[0m in 1.86s]
[2022-06-20 23:11:19,701] {subprocess.py:89} INFO - 23:11:19  5 of 16 OK created incremental model PUBLIC.final_match_info ................... [[32mSUCCESS 1[0m in 4.40s]
[2022-06-20 23:11:19,702] {subprocess.py:89} INFO - 23:11:19  15 of 16 START view model PUBLIC.stg_runes_reforged ............................ [RUN]
[2022-06-20 23:11:19,709] {subprocess.py:89} INFO - 23:11:19  16 of 16 START view model PUBLIC.stg_summonerspells ............................ [RUN]
[2022-06-20 23:11:20,238] {subprocess.py:89} INFO - 23:11:20  3 of 16 OK created table model PUBLIC.final_maps ............................... [[32mSUCCESS 1[0m in 4.78s]
[2022-06-20 23:11:20,279] {subprocess.py:89} INFO - 23:11:20  7 of 16 OK created table model PUBLIC.final_runes_reforged ..................... [[32mSUCCESS 1[0m in 4.81s]
[2022-06-20 23:11:20,300] {subprocess.py:89} INFO - 23:11:20  8 of 16 OK created table model PUBLIC.final_summonerspells ..................... [[32mSUCCESS 1[0m in 4.82s]
[2022-06-20 23:11:20,327] {subprocess.py:89} INFO - 23:11:20  13 of 16 OK created view model PUBLIC.stg_match_info ........................... [[32mSUCCESS 1[0m in 1.18s]
[2022-06-20 23:11:20,350] {subprocess.py:89} INFO - 23:11:20  12 of 16 OK created view model PUBLIC.stg_match_details ........................ [[32mSUCCESS 1[0m in 1.32s]
[2022-06-20 23:11:20,474] {subprocess.py:89} INFO - 23:11:20  2 of 16 OK created table model PUBLIC.final_items .............................. [[32mSUCCESS 1[0m in 5.16s]
[2022-06-20 23:11:20,956] {subprocess.py:89} INFO - 23:11:20  16 of 16 OK created view model PUBLIC.stg_summonerspells ....................... [[32mSUCCESS 1[0m in 1.25s]
[2022-06-20 23:11:20,976] {subprocess.py:89} INFO - 23:11:20  15 of 16 OK created view model PUBLIC.stg_runes_reforged ....................... [[32mSUCCESS 1[0m in 1.27s]
[2022-06-20 23:11:21,004] {subprocess.py:89} INFO - 23:11:21  14 of 16 OK created view model PUBLIC.stg_players .............................. [[32mSUCCESS 1[0m in 1.36s]
[2022-06-20 23:11:22,156] {subprocess.py:89} INFO - 23:11:22  4 of 16 ERROR creating incremental model PUBLIC.final_match_details ............ [[31mERROR[0m in 6.86s]
[2022-06-20 23:11:22,159] {subprocess.py:89} INFO - 23:11:22
[2022-06-20 23:11:22,159] {subprocess.py:89} INFO - 23:11:22  Finished running 5 table models, 8 view models, 3 incremental models in 8.45s.
[2022-06-20 23:11:22,175] {subprocess.py:89} INFO - 23:11:22
[2022-06-20 23:11:22,176] {subprocess.py:89} INFO - 23:11:22  [31mCompleted with 1 error and 0 warnings:[0m
[2022-06-20 23:11:22,176] {subprocess.py:89} INFO - 23:11:22
[2022-06-20 23:11:22,176] {subprocess.py:89} INFO - 23:11:22  [33mDatabase Error in model final_match_details (models/warehouse/final_match_details.sql)[0m
[2022-06-20 23:11:22,177] {subprocess.py:89} INFO - 23:11:22    100038 (22018): Numeric value 'TOP' is not recognized
[2022-06-20 23:11:22,177] {subprocess.py:89} INFO - 23:11:22    compiled SQL at target/run/leagueoflegendsdbt/models/warehouse/final_match_details.sql
[2022-06-20 23:11:22,177] {subprocess.py:89} INFO - 23:11:22
[2022-06-20 23:11:22,178] {subprocess.py:89} INFO - 23:11:22  Done. PASS=15 WARN=0 ERROR=1 SKIP=0 TOTAL=16
[2022-06-20 23:11:22,876] {subprocess.py:93} INFO - Command exited with return code 1
[2022-06-20 23:11:22,887] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 23:11:22,892] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=match_details_dag, task_id=dbt_run, execution_date=20220620T010000, start_date=20220620T231105, end_date=20220620T231122
[2022-06-20 23:11:22,904] {standard_task_runner.py:89} ERROR - Failed to execute job 217 for task dbt_run
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 23:11:22,922] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-20 23:11:22,950] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
