[2022-05-19 08:19:59,289] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_summonerspells.staging_summonerspells scheduled__2022-03-31T23:00:00+00:00 [queued]>
[2022-05-19 08:19:59,300] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_summonerspells.staging_summonerspells scheduled__2022-03-31T23:00:00+00:00 [queued]>
[2022-05-19 08:19:59,301] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 08:19:59,301] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 08:19:59,301] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 08:19:59,312] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_summonerspells.staging_summonerspells> on 2022-03-31 23:00:00+00:00
[2022-05-19 08:19:59,318] {standard_task_runner.py:52} INFO - Started process 1416 to run task
[2022-05-19 08:19:59,321] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_summonerspells.staging_summonerspells', 'scheduled__2022-03-31T23:00:00+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpfhvj4qkp', '--error-file', '/tmp/tmp6uoq7zfp']
[2022-05-19 08:19:59,322] {standard_task_runner.py:77} INFO - Job 260: Subtask paths.path_summonerspells.staging_summonerspells
[2022-05-19 08:19:59,369] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_summonerspells.staging_summonerspells scheduled__2022-03-31T23:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 08:19:59,417] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_summonerspells.staging_summonerspells
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T23:00:00+00:00
[2022-05-19 08:19:59,417] {riot_datadragon_toADLS_Operator.py:54} INFO - StageToAzureLake not implemented yet
[2022-05-19 08:19:59,426] {riot_datadragon_toADLS_Operator.py:62} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7fdd8b2dcfa0>>
[2022-05-19 08:19:59,427] {riot_datadragon_toADLS_Operator.py:63} INFO - Created Azure Connections
[2022-05-19 08:19:59,514] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 55, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 90, in upload_to_azureLake
    year=self.end_epoch.year,
AttributeError: 'int' object has no attribute 'year'
[2022-05-19 08:19:59,527] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_summonerspells.staging_summonerspells, execution_date=20220331T230000, start_date=20220519T081959, end_date=20220519T081959
[2022-05-19 08:19:59,544] {standard_task_runner.py:89} ERROR - Failed to execute job 260 for task paths.path_summonerspells.staging_summonerspells
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 55, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 90, in upload_to_azureLake
    year=self.end_epoch.year,
AttributeError: 'int' object has no attribute 'year'
[2022-05-19 08:19:59,574] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 08:19:59,607] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
