[2022-06-15 18:22:41,073] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.dbt_run manual__2022-06-15T00:01:53.911524+00:00 [None]>
[2022-06-15 18:22:41,097] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.dbt_run manual__2022-06-15T00:01:53.911524+00:00 [None]>
[2022-06-15 18:22:41,097] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 18:22:41,098] {taskinstance.py:1244} INFO - Starting attempt 7 of 8
[2022-06-15 18:22:41,098] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 18:22:41,118] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt_run> on 2022-06-15 00:01:53.911524+00:00
[2022-06-15 18:22:41,125] {standard_task_runner.py:52} INFO - Started process 259 to run task
[2022-06-15 18:22:41,128] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'dbt_run', 'manual__2022-06-15T00:01:53.911524+00:00', '--job-id', '124', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmp8mkznd4a', '--error-file', '/tmp/tmp20i9yuuw']
[2022-06-15 18:22:41,129] {standard_task_runner.py:77} INFO - Job 124: Subtask dbt_run
[2022-06-15 18:22:41,198] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.dbt_run manual__2022-06-15T00:01:53.911524+00:00 [running]> on host ebe3cc7dbee2
[2022-06-15 18:22:41,275] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T00:01:53.911524+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T00:01:53.911524+00:00
[2022-06-15 18:22:41,278] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-15 18:22:41,279] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/dbt && dbt deps && dbt run']
[2022-06-15 18:22:41,298] {subprocess.py:85} INFO - Output:
[2022-06-15 18:22:46,573] {subprocess.py:89} INFO - 18:22:46  Running with dbt=1.1.0
[2022-06-15 18:22:47,066] {subprocess.py:89} INFO - 18:22:47  Installing dbt-labs/dbt_utils
[2022-06-15 18:22:47,673] {subprocess.py:89} INFO - 18:22:47    Installed from version 0.8.5
[2022-06-15 18:22:47,674] {subprocess.py:89} INFO - 18:22:47    Up to date!
[2022-06-15 18:22:52,756] {subprocess.py:89} INFO - 18:22:52  Running with dbt=1.1.0
[2022-06-15 18:22:53,033] {subprocess.py:89} INFO - 18:22:53  Found 14 models, 28 tests, 0 snapshots, 0 analyses, 400 macros, 0 operations, 0 seed files, 14 sources, 0 exposures, 0 metrics
[2022-06-15 18:22:53,037] {subprocess.py:89} INFO - 18:22:53
[2022-06-15 18:22:54,795] {subprocess.py:89} INFO - 18:22:54  Concurrency: 10 threads (target='dev')
[2022-06-15 18:22:54,795] {subprocess.py:89} INFO - 18:22:54
[2022-06-15 18:22:54,818] {subprocess.py:89} INFO - 18:22:54  1 of 14 START table model PUBLIC.final_champions ............................... [RUN]
[2022-06-15 18:22:54,822] {subprocess.py:89} INFO - 18:22:54  2 of 14 START table model PUBLIC.final_items ................................... [RUN]
[2022-06-15 18:22:54,825] {subprocess.py:89} INFO - 18:22:54  3 of 14 START table model PUBLIC.final_maps .................................... [RUN]
[2022-06-15 18:22:54,827] {subprocess.py:89} INFO - 18:22:54  4 of 14 START incremental model PUBLIC.final_match_details ..................... [RUN]
[2022-06-15 18:22:54,829] {subprocess.py:89} INFO - 18:22:54  5 of 14 START incremental model PUBLIC.final_match_info ........................ [RUN]
[2022-06-15 18:22:54,829] {subprocess.py:89} INFO - 18:22:54  6 of 14 START table model PUBLIC.final_runes_reforged .......................... [RUN]
[2022-06-15 18:22:54,830] {subprocess.py:89} INFO - 18:22:54  7 of 14 START table model PUBLIC.final_summonerspells .......................... [RUN]
[2022-06-15 18:22:54,832] {subprocess.py:89} INFO - 18:22:54  8 of 14 START view model PUBLIC.stg_champions .................................. [RUN]
[2022-06-15 18:22:54,833] {subprocess.py:89} INFO - 18:22:54  9 of 14 START view model PUBLIC.stg_items ...................................... [RUN]
[2022-06-15 18:22:54,834] {subprocess.py:89} INFO - 18:22:54  10 of 14 START view model PUBLIC.stg_maps ...................................... [RUN]
[2022-06-15 18:22:59,356] {subprocess.py:89} INFO - 18:22:59  5 of 14 OK created incremental model PUBLIC.final_match_info ................... [[32mSUCCESS 1[0m in 4.52s]
[2022-06-15 18:22:59,359] {subprocess.py:89} INFO - 18:22:59  11 of 14 START view model PUBLIC.stg_match_details ............................. [RUN]
[2022-06-15 18:22:59,901] {subprocess.py:89} INFO - 18:22:59  6 of 14 OK created table model PUBLIC.final_runes_reforged ..................... [[32mSUCCESS 1[0m in 5.06s]
[2022-06-15 18:22:59,904] {subprocess.py:89} INFO - 18:22:59  8 of 14 OK created view model PUBLIC.stg_champions ............................. [[32mSUCCESS 1[0m in 5.06s]
[2022-06-15 18:22:59,908] {subprocess.py:89} INFO - 18:22:59  10 of 14 OK created view model PUBLIC.stg_maps ................................. [[32mSUCCESS 1[0m in 5.06s]
[2022-06-15 18:22:59,911] {subprocess.py:89} INFO - 18:22:59  3 of 14 OK created table model PUBLIC.final_maps ............................... [[32mSUCCESS 1[0m in 5.08s]
[2022-06-15 18:22:59,912] {subprocess.py:89} INFO - 18:22:59  9 of 14 OK created view model PUBLIC.stg_items ................................. [[32mSUCCESS 1[0m in 5.07s]
[2022-06-15 18:22:59,913] {subprocess.py:89} INFO - 18:22:59  12 of 14 START view model PUBLIC.stg_match_info ................................ [RUN]
[2022-06-15 18:22:59,915] {subprocess.py:89} INFO - 18:22:59  13 of 14 START view model PUBLIC.stg_runes_reforged ............................ [RUN]
[2022-06-15 18:22:59,917] {subprocess.py:89} INFO - 18:22:59  14 of 14 START view model PUBLIC.stg_summonerspells ............................ [RUN]
[2022-06-15 18:22:59,963] {subprocess.py:89} INFO - 18:22:59  2 of 14 ERROR creating table model PUBLIC.final_items .......................... [[31mERROR[0m in 5.12s]
[2022-06-15 18:23:00,776] {subprocess.py:89} INFO - 18:23:00  1 of 14 OK created table model PUBLIC.final_champions .......................... [[32mSUCCESS 1[0m in 5.96s]
[2022-06-15 18:23:00,823] {subprocess.py:89} INFO - 18:23:00  11 of 14 OK created view model PUBLIC.stg_match_details ........................ [[32mSUCCESS 1[0m in 1.46s]
[2022-06-15 18:23:00,935] {subprocess.py:89} INFO - 18:23:00  7 of 14 OK created table model PUBLIC.final_summonerspells ..................... [[32mSUCCESS 1[0m in 6.10s]
[2022-06-15 18:23:01,363] {subprocess.py:89} INFO - 18:23:01  12 of 14 OK created view model PUBLIC.stg_match_info ........................... [[32mSUCCESS 1[0m in 1.45s]
[2022-06-15 18:23:01,477] {subprocess.py:89} INFO - 18:23:01  13 of 14 OK created view model PUBLIC.stg_runes_reforged ....................... [[32mSUCCESS 1[0m in 1.56s]
[2022-06-15 18:23:01,481] {subprocess.py:89} INFO - 18:23:01  14 of 14 OK created view model PUBLIC.stg_summonerspells ....................... [[32mSUCCESS 1[0m in 1.56s]
[2022-06-15 18:23:02,710] {subprocess.py:89} INFO - 18:23:02  4 of 14 OK created incremental model PUBLIC.final_match_details ................ [[32mSUCCESS 1[0m in 7.88s]
[2022-06-15 18:23:02,715] {subprocess.py:89} INFO - 18:23:02
[2022-06-15 18:23:02,715] {subprocess.py:89} INFO - 18:23:02  Finished running 2 incremental models, 5 table models, 7 view models in 9.68s.
[2022-06-15 18:23:02,732] {subprocess.py:89} INFO - 18:23:02
[2022-06-15 18:23:02,732] {subprocess.py:89} INFO - 18:23:02  [31mCompleted with 1 error and 0 warnings:[0m
[2022-06-15 18:23:02,733] {subprocess.py:89} INFO - 18:23:02
[2022-06-15 18:23:02,733] {subprocess.py:89} INFO - 18:23:02  [33mDatabase Error in model final_items (models/warehouse/final_items.sql)[0m
[2022-06-15 18:23:02,733] {subprocess.py:89} INFO - 18:23:02    000904 (42000): SQL compilation error: error line 20 at position 8
[2022-06-15 18:23:02,734] {subprocess.py:89} INFO - 18:23:02    invalid identifier 'FLATHPPOOLMOD'
[2022-06-15 18:23:02,734] {subprocess.py:89} INFO - 18:23:02    compiled SQL at target/run/leagueoflegendsdbt/models/warehouse/final_items.sql
[2022-06-15 18:23:02,734] {subprocess.py:89} INFO - 18:23:02
[2022-06-15 18:23:02,735] {subprocess.py:89} INFO - 18:23:02  Done. PASS=13 WARN=0 ERROR=1 SKIP=0 TOTAL=14
[2022-06-15 18:23:03,513] {subprocess.py:93} INFO - Command exited with return code 1
[2022-06-15 18:23:03,525] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-15 18:23:03,530] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=match_details_dag, task_id=dbt_run, execution_date=20220615T000153, start_date=20220615T182241, end_date=20220615T182303
[2022-06-15 18:23:03,545] {standard_task_runner.py:89} ERROR - Failed to execute job 124 for task dbt_run
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-15 18:23:03,562] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-15 18:23:03,593] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
