[2022-06-15 19:38:55,103] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.dbt_run manual__2022-06-15T00:01:53.911524+00:00 [None]>
[2022-06-15 19:38:55,113] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.dbt_run manual__2022-06-15T00:01:53.911524+00:00 [None]>
[2022-06-15 19:38:55,113] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 19:38:55,113] {taskinstance.py:1244} INFO - Starting attempt 8 of 9
[2022-06-15 19:38:55,113] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 19:38:55,124] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt_run> on 2022-06-15 00:01:53.911524+00:00
[2022-06-15 19:38:55,132] {standard_task_runner.py:52} INFO - Started process 316 to run task
[2022-06-15 19:38:55,135] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'dbt_run', 'manual__2022-06-15T00:01:53.911524+00:00', '--job-id', '125', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmpcgtlv71q', '--error-file', '/tmp/tmph2wr6t30']
[2022-06-15 19:38:55,136] {standard_task_runner.py:77} INFO - Job 125: Subtask dbt_run
[2022-06-15 19:38:55,195] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.dbt_run manual__2022-06-15T00:01:53.911524+00:00 [running]> on host ebe3cc7dbee2
[2022-06-15 19:38:55,238] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T00:01:53.911524+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T00:01:53.911524+00:00
[2022-06-15 19:38:55,239] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-15 19:38:55,240] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/dbt && dbt deps && dbt run']
[2022-06-15 19:38:55,248] {subprocess.py:85} INFO - Output:
[2022-06-15 19:38:58,464] {subprocess.py:89} INFO - 19:38:58  Running with dbt=1.1.0
[2022-06-15 19:38:59,219] {subprocess.py:89} INFO - 19:38:59  Installing dbt-labs/dbt_utils
[2022-06-15 19:38:59,821] {subprocess.py:89} INFO - 19:38:59    Installed from version 0.8.5
[2022-06-15 19:38:59,821] {subprocess.py:89} INFO - 19:38:59    Up to date!
[2022-06-15 19:39:05,045] {subprocess.py:89} INFO - 19:39:05  Running with dbt=1.1.0
[2022-06-15 19:39:05,212] {subprocess.py:89} INFO - 19:39:05  Found 14 models, 28 tests, 0 snapshots, 0 analyses, 400 macros, 0 operations, 0 seed files, 14 sources, 0 exposures, 0 metrics
[2022-06-15 19:39:05,216] {subprocess.py:89} INFO - 19:39:05
[2022-06-15 19:39:07,268] {subprocess.py:89} INFO - 19:39:07  Concurrency: 10 threads (target='dev')
[2022-06-15 19:39:07,268] {subprocess.py:89} INFO - 19:39:07
[2022-06-15 19:39:07,292] {subprocess.py:89} INFO - 19:39:07  1 of 14 START table model PUBLIC.final_champions ............................... [RUN]
[2022-06-15 19:39:07,296] {subprocess.py:89} INFO - 19:39:07  2 of 14 START table model PUBLIC.final_items ................................... [RUN]
[2022-06-15 19:39:07,299] {subprocess.py:89} INFO - 19:39:07  3 of 14 START table model PUBLIC.final_maps .................................... [RUN]
[2022-06-15 19:39:07,300] {subprocess.py:89} INFO - 19:39:07  4 of 14 START incremental model PUBLIC.final_match_details ..................... [RUN]
[2022-06-15 19:39:07,301] {subprocess.py:89} INFO - 19:39:07  5 of 14 START incremental model PUBLIC.final_match_info ........................ [RUN]
[2022-06-15 19:39:07,301] {subprocess.py:89} INFO - 19:39:07  6 of 14 START table model PUBLIC.final_runes_reforged .......................... [RUN]
[2022-06-15 19:39:07,303] {subprocess.py:89} INFO - 19:39:07  7 of 14 START table model PUBLIC.final_summonerspells .......................... [RUN]
[2022-06-15 19:39:07,304] {subprocess.py:89} INFO - 19:39:07  8 of 14 START view model PUBLIC.stg_champions .................................. [RUN]
[2022-06-15 19:39:07,304] {subprocess.py:89} INFO - 19:39:07  9 of 14 START view model PUBLIC.stg_items ...................................... [RUN]
[2022-06-15 19:39:07,305] {subprocess.py:89} INFO - 19:39:07  10 of 14 START view model PUBLIC.stg_maps ...................................... [RUN]
[2022-06-15 19:39:11,553] {subprocess.py:89} INFO - 19:39:11  3 of 14 OK created table model PUBLIC.final_maps ............................... [[32mSUCCESS 1[0m in 4.24s]
[2022-06-15 19:39:11,557] {subprocess.py:89} INFO - 19:39:11  11 of 14 START view model PUBLIC.stg_match_details ............................. [RUN]
[2022-06-15 19:39:11,999] {subprocess.py:89} INFO - 19:39:11  8 of 14 OK created view model PUBLIC.stg_champions ............................. [[32mSUCCESS 1[0m in 4.69s]
[2022-06-15 19:39:12,004] {subprocess.py:89} INFO - 19:39:12  12 of 14 START view model PUBLIC.stg_match_info ................................ [RUN]
[2022-06-15 19:39:12,005] {subprocess.py:89} INFO - 19:39:12  2 of 14 ERROR creating table model PUBLIC.final_items .......................... [[31mERROR[0m in 4.71s]
[2022-06-15 19:39:12,030] {subprocess.py:89} INFO - 19:39:12  13 of 14 START view model PUBLIC.stg_runes_reforged ............................ [RUN]
[2022-06-15 19:39:12,093] {subprocess.py:89} INFO - 19:39:12  10 of 14 OK created view model PUBLIC.stg_maps ................................. [[32mSUCCESS 1[0m in 4.73s]
[2022-06-15 19:39:12,113] {subprocess.py:89} INFO - 19:39:12  9 of 14 OK created view model PUBLIC.stg_items ................................. [[32mSUCCESS 1[0m in 4.78s]
[2022-06-15 19:39:12,123] {subprocess.py:89} INFO - 19:39:12  14 of 14 START view model PUBLIC.stg_summonerspells ............................ [RUN]
[2022-06-15 19:39:12,891] {subprocess.py:89} INFO - 19:39:12  6 of 14 OK created table model PUBLIC.final_runes_reforged ..................... [[32mSUCCESS 1[0m in 5.53s]
[2022-06-15 19:39:12,902] {subprocess.py:89} INFO - 19:39:12  1 of 14 OK created table model PUBLIC.final_champions .......................... [[32mSUCCESS 1[0m in 5.60s]
[2022-06-15 19:39:12,927] {subprocess.py:89} INFO - 19:39:12  11 of 14 OK created view model PUBLIC.stg_match_details ........................ [[32mSUCCESS 1[0m in 1.37s]
[2022-06-15 19:39:12,980] {subprocess.py:89} INFO - 19:39:12  7 of 14 OK created table model PUBLIC.final_summonerspells ..................... [[32mSUCCESS 1[0m in 5.67s]
[2022-06-15 19:39:13,447] {subprocess.py:89} INFO - 19:39:13  12 of 14 OK created view model PUBLIC.stg_match_info ........................... [[32mSUCCESS 1[0m in 1.44s]
[2022-06-15 19:39:13,467] {subprocess.py:89} INFO - 19:39:13  4 of 14 OK created incremental model PUBLIC.final_match_details ................ [[32mSUCCESS 1[0m in 6.16s]
[2022-06-15 19:39:13,476] {subprocess.py:89} INFO - 19:39:13  14 of 14 OK created view model PUBLIC.stg_summonerspells ....................... [[32mSUCCESS 1[0m in 1.35s]
[2022-06-15 19:39:13,531] {subprocess.py:89} INFO - 19:39:13  13 of 14 OK created view model PUBLIC.stg_runes_reforged ....................... [[32mSUCCESS 1[0m in 1.50s]
[2022-06-15 19:39:13,634] {subprocess.py:89} INFO - 19:39:13  5 of 14 OK created incremental model PUBLIC.final_match_info ................... [[32mSUCCESS 1[0m in 6.33s]
[2022-06-15 19:39:13,638] {subprocess.py:89} INFO - 19:39:13
[2022-06-15 19:39:13,638] {subprocess.py:89} INFO - 19:39:13  Finished running 5 table models, 7 view models, 2 incremental models in 8.42s.
[2022-06-15 19:39:13,654] {subprocess.py:89} INFO - 19:39:13
[2022-06-15 19:39:13,654] {subprocess.py:89} INFO - 19:39:13  [31mCompleted with 1 error and 0 warnings:[0m
[2022-06-15 19:39:13,655] {subprocess.py:89} INFO - 19:39:13
[2022-06-15 19:39:13,655] {subprocess.py:89} INFO - 19:39:13  [33mDatabase Error in model final_items (models/warehouse/final_items.sql)[0m
[2022-06-15 19:39:13,655] {subprocess.py:89} INFO - 19:39:13    001003 (42000): SQL compilation error:
[2022-06-15 19:39:13,656] {subprocess.py:89} INFO - 19:39:13    syntax error line 16 at position 16 unexpected ''Summoners Rift''.
[2022-06-15 19:39:13,656] {subprocess.py:89} INFO - 19:39:13    syntax error line 17 at position 16 unexpected ''Howling Abyss''.
[2022-06-15 19:39:13,657] {subprocess.py:89} INFO - 19:39:13    syntax error line 18 at position 16 unexpected ''Nexus Blitz''.
[2022-06-15 19:39:13,657] {subprocess.py:89} INFO - 19:39:13    syntax error line 19 at position 16 unexpected ''Teamfight Tactics''.
[2022-06-15 19:39:13,657] {subprocess.py:89} INFO - 19:39:13    syntax error line 85 at position 4 unexpected 'FROM'.
[2022-06-15 19:39:13,658] {subprocess.py:89} INFO - 19:39:13    compiled SQL at target/run/leagueoflegendsdbt/models/warehouse/final_items.sql
[2022-06-15 19:39:13,658] {subprocess.py:89} INFO - 19:39:13
[2022-06-15 19:39:13,659] {subprocess.py:89} INFO - 19:39:13  Done. PASS=13 WARN=0 ERROR=1 SKIP=0 TOTAL=14
[2022-06-15 19:39:14,347] {subprocess.py:93} INFO - Command exited with return code 1
[2022-06-15 19:39:14,358] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-15 19:39:14,363] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=match_details_dag, task_id=dbt_run, execution_date=20220615T000153, start_date=20220615T193855, end_date=20220615T193914
[2022-06-15 19:39:14,375] {standard_task_runner.py:89} ERROR - Failed to execute job 125 for task dbt_run
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-15 19:39:14,403] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-15 19:39:14,433] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
